options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: python:3.11-slim
    id: test
    entrypoint: bash
    args:
      - -c
      - |
        # install core Airflow plus the GCP provider and clients
        pip install apache-airflow==2.10.5 \
                    apache-airflow-providers-google \
                    google-cloud-storage \
                    google-cloud-bigquery \
                    pytest

  - name: 'gcr.io/cloud-builders/docker'
    id: build-img
    args:
      - build
      - '-t'
      - europe-west3-docker.pkg.dev/$PROJECT_ID/thesis-docker/datagenerator:$COMMIT_SHA
      - .
  - name: 'gcr.io/cloud-builders/docker'
    id: push-img
    args:
      - push
      - europe-west3-docker.pkg.dev/$PROJECT_ID/thesis-docker/datagenerator:$COMMIT_SHA

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: sync-dags
    entrypoint: bash
    args:
      - -c
      - |
        gsutil -m cp -r dags/*.py gs://europe-west3-thesis-compose-2dd8c22b-bucket/dags/

timeout: 1200s
